### PR TITLE
add types file

### LINKED ISSUE #2: Add types file
Add typescript types file (perhaps rewrite the project into typescript, it's only small) and include with the project.

### PR DESCRIPTION
**Pull request by marcelorl**
Closes #2 

As required:

 - Added types file
 - Rewrote the project into typescript
 - Even tests are in typescript as well

Bonus:

 - Code coverage command
 - Added the `npm run test:coverage` command to .travis.yml, so that, it shouldnt be possible to merge anything if tests get broken

Upgraded version to 1.3.0 since it was added the new `extract` method.

### CODE REVIEW

**Comment by joshghent** [comment]
Wow this is awesome! Thanks dude 🎉 A lot of work went into this, it's great. I've invited you to be a collaborator on the project so you can maintain the project if you so wish. I don't have a great deal of time for it, but if you would like to work on it, I would very much appreciate that!

Question though, do we need the dist and typings folder?

**Comment by marcelorl** [comment]
hi @joshghent you are absolutely right.

I worked in a solution for this, please have a look.

I took in consideration the following repos:

https://github.com/bitjson/typescript-starter
https://github.com/Microsoft/TypeScript-Node-Starter

What are you thoughts?

**Comment by joshghent** [comment]
@marcelorl After reviewing this again, looks fantastic. Thanks so much for doing this. Nice job converting all the files! That can't have been easy! Great work as always mate 🎉 I'm happy for this to be merged. There seems to be some weird MR conflicts, but that just seems like docs so should be a quick fix. Thanks again, go ahead and merge this as soon as you can 👍

**Comment by marcelorl** [comment]
Hi @joshghent I was out for few days haha...

I'm back again.

Can you review my changes?

I have fixed/merged all conflicts from last PR.

**Comment by joshghent** [comment]
@marcelorl This is amazing, thanks again for this! It's a huge help! 👍 Hope you had a nice time away :)

**Pull request merged**
